"""Полный стартовый каталог для БД (≈30 объявлений с фото)."""

from app.media_urls import gallery_for_index

_RAW = [
    {
        "title": "Генератор Toyota Camry 40 2.4",
        "part_number": "27060-0H010",
        "price": 8500,
        "condition": "used",
        "category": "electrical",
        "car": "Toyota Camry",
        "fits": ["Toyota Camry 40 (2006–2011)", "Toyota Camry 50", "Lexus ES350"],
        "location": "рынок Кудайберген",
        "address": "рынок Кудайберген, ряд 12",
        "seller_name": "Азамат К.",
        "phone": "+996555100101",
        "working_hours": "09:00–18:00, без выходных",
        "description": "Рабочий генератор, снят с Camry 40.",
        "verified": True,
        "attributes": {"Тип": "Генератор", "Состояние": "Б/У", "Проверка": "Стенд"},
    },
    {
        "title": "Передний бампер Honda Accord 8",
        "part_number": "71110-TA0-A00",
        "price": 12000,
        "condition": "used",
        "category": "general",
        "car": "Honda Accord",
        "fits": ["Honda Accord 8 (2008–2012)"],
        "location": "Джал",
        "seller_name": "Разбор «Авто+»",
        "phone": "+996555200202",
        "verified": True,
    },
    {
        "title": "Двигатель 1NZ-FE 1.5 б/у",
        "part_number": "1NZ-FE",
        "price": 95000,
        "condition": "used",
        "category": "engine",
        "car": "Toyota",
        "fits": ["Toyota Vitz", "Toyota Platz", "Toyota Yaris"],
        "location": "рынок Кудайберген",
        "seller_name": "Эрлан М.",
        "phone": "+996555300303",
        "description": "Комплектность уточняйте по телефону",
        "verified": True,
    },
    {
        "title": "Тормозные колодки передние — новые",
        "part_number": "04465-02220",
        "price": 3200,
        "condition": "new",
        "category": "general",
        "car": "универсальные",
        "fits": ["Toyota Corolla", "Toyota Auris"],
        "location": "Орто-Сай",
        "seller_name": "Импорт KG",
        "verified": True,
    },
    {
        "title": "Фара левая Hyundai Solaris",
        "part_number": "92101-4L000",
        "price": 6500,
        "condition": "used",
        "category": "general",
        "car": "Hyundai Solaris",
        "fits": ["Hyundai Solaris 2010–2017"],
        "location": "рынок Кудайберген",
        "seller_name": "Бакыт Т.",
        "verified": True,
    },
    {
        "title": "Стартер Nissan Almera Classic",
        "part_number": "23300-EE00A",
        "price": 4800,
        "condition": "used",
        "category": "electrical",
        "car": "Nissan Almera",
        "location": "Асанбай",
        "seller_name": "Нурбек А.",
        "verified": True,
    },
    {
        "title": "Радиатор охлаждения Mercedes W210",
        "part_number": "2105000303",
        "price": 15000,
        "condition": "used",
        "category": "cooling",
        "car": "Mercedes E-class",
        "location": "рынок Кудайберген",
        "seller_name": "Разбор «Авто+»",
        "verified": True,
    },
    {
        "title": "Амортизатор передний левый VW Polo",
        "part_number": "6R0413031",
        "price": 5500,
        "condition": "used",
        "category": "suspension",
        "car": "VW Polo",
        "location": "Джал",
        "seller_name": "Азамат К.",
        "verified": True,
    },
    {
        "title": "АКПП Toyota Corolla 120",
        "part_number": "U341E",
        "price": 45000,
        "condition": "used",
        "category": "transmission",
        "car": "Toyota Corolla",
        "fits": ["Toyota Corolla 120", "Toyota Auris"],
        "location": "рынок Кудайберген",
        "seller_name": "Бакыт Т.",
        "verified": True,
    },
    {
        "title": "Магнитола Pioneer 2 DIN",
        "part_number": "AVH-Z5200D",
        "price": 5500,
        "condition": "used",
        "category": "electrical",
        "car": "универсальная",
        "location": "Асанбай",
        "seller_name": "Нурбек А.",
        "verified": True,
    },
    {
        "title": "Диски литые R17 5x114.3 (комплект 4 шт.)",
        "part_number": "R17-5x114.3-ET38",
        "price": 28000,
        "condition": "used",
        "category": "wheels_tires",
        "car": "универсальные",
        "fits": ["Toyota", "Hyundai", "Kia (5x114.3)"],
        "location": "Орто-Сай",
        "seller_name": "Айбек Wheels",
        "verified": True,
    },
    {
        "title": "Шины летние 205/55 R16 (2 шт.)",
        "part_number": "205/55R16-SUMMER",
        "price": 9000,
        "condition": "used",
        "category": "wheels_tires",
        "car": "универсальные",
        "location": "Джал",
        "seller_name": "Tire Market",
        "verified": False,
    },
    {
        "title": "Капот Toyota RAV4 2015",
        "part_number": "53301-0R050",
        "price": 18500,
        "condition": "used",
        "category": "general",
        "car": "Toyota RAV4",
        "location": "рынок Кудайберген",
        "seller_name": "Разбор «Авто+»",
        "verified": True,
    },
    {
        "title": "Компрессор кондиционера Kia Rio",
        "part_number": "97701-1R000",
        "price": 14000,
        "condition": "used",
        "category": "cooling",
        "car": "Kia Rio",
        "location": "Джал",
        "seller_name": "Азамат К.",
        "verified": True,
    },
    {
        "title": "Рулевая рейка Honda CR-V",
        "part_number": "53601-SWA-A03",
        "price": 22000,
        "condition": "used",
        "category": "suspension",
        "car": "Honda CR-V",
        "location": "Асанбай",
        "seller_name": "Эрлан М.",
        "verified": False,
    },
    {
        "title": "Фары LED комплект (универсальные)",
        "part_number": "LED-H7-KIT",
        "price": 4500,
        "condition": "new",
        "category": "electrical",
        "car": "универсальные",
        "location": "Орто-Сай",
        "seller_name": "Импорт KG",
        "verified": True,
    },
    {
        "title": "Шины Michelin 225/45 R17 (комплект 4)",
        "part_number": "225/45R17-MIC",
        "price": 32000,
        "condition": "used",
        "category": "wheels_tires",
        "car": "универсальные",
        "location": "Орто-Сай",
        "seller_name": "Tire Market",
        "verified": True,
    },
    {
        "title": "Шины зимние Nokian 195/65 R15",
        "part_number": "195/65R15-NOK",
        "price": 18000,
        "condition": "used",
        "category": "wheels_tires",
        "car": "универсальные",
        "location": "Джал",
        "seller_name": "Tire Pro",
        "verified": True,
    },
    {
        "title": "Шины Bridgestone 215/60 R16",
        "part_number": "215/60R16-BRI",
        "price": 14000,
        "condition": "used",
        "category": "wheels_tires",
        "car": "SUV",
        "location": "рынок Кудайберген",
        "seller_name": "Айбек Wheels",
        "verified": False,
    },
    {
        "title": "Диски BBS R18 5x112 (2 шт.)",
        "part_number": "R18-5x112-BBS",
        "price": 42000,
        "condition": "used",
        "category": "wheels_tires",
        "car": "VW / Audi",
        "location": "Орто-Сай",
        "seller_name": "Айбек Wheels",
        "verified": True,
    },
    {
        "title": "Диски штампованные R15 4x100",
        "part_number": "R15-4x100-ST",
        "price": 12000,
        "condition": "used",
        "category": "wheels_tires",
        "car": "универсальные",
        "location": "Джал",
        "seller_name": "Айбек Wheels",
        "verified": True,
    },
    {
        "title": "Сиденья передние Toyota Prius 20",
        "part_number": "SEAT-PRIUS20",
        "price": 16000,
        "condition": "used",
        "category": "interior",
        "car": "Toyota Prius",
        "location": "Асанбай",
        "seller_name": "Разбор «Авто+»",
        "verified": True,
    },
    {
        "title": "Турбина VW Passat B6 2.0 TDI",
        "part_number": "03G253019",
        "price": 38000,
        "condition": "used",
        "category": "engine",
        "car": "VW Passat",
        "location": "рынок Кудайберген",
        "seller_name": "Эрлан М.",
        "verified": True,
    },
    {
        "title": "Катализатор Subaru Forester",
        "part_number": "SUB-CAT-FORESTER",
        "price": 25000,
        "condition": "used",
        "category": "engine",
        "car": "Subaru Forester",
        "location": "Джал",
        "seller_name": "Нурбек А.",
        "verified": False,
    },
    {
        "title": "Тормозной диск передний Mazda 3",
        "part_number": "BKY233251Z",
        "price": 4200,
        "condition": "used",
        "category": "general",
        "car": "Mazda 3",
        "location": "Орто-Сай",
        "seller_name": "Импорт KG",
        "verified": True,
    },
    {
        "title": "Насос ГУР Lexus RX350",
        "part_number": "44310-48070",
        "price": 11000,
        "condition": "used",
        "category": "suspension",
        "car": "Lexus RX",
        "location": "рынок Кудайберген",
        "seller_name": "Азамат К.",
        "verified": True,
    },
    {
        "title": "Вентилятор охлаждения Ford Focus 2",
        "part_number": "FORD-FAN-FOCUS2",
        "price": 7500,
        "condition": "used",
        "category": "cooling",
        "car": "Ford Focus",
        "location": "Асанбай",
        "seller_name": "Бакыт Т.",
        "verified": True,
    },
    {
        "title": "МКПП Hyundai Accent MC",
        "part_number": "M5AF1-Accent",
        "price": 52000,
        "condition": "used",
        "category": "transmission",
        "car": "Hyundai Accent",
        "location": "Джал",
        "seller_name": "Разбор «Авто+»",
        "verified": True,
    },
    {
        "title": "Зеркало правое Kia Sportage 2016",
        "part_number": "87620-D3000",
        "price": 6800,
        "condition": "used",
        "category": "general",
        "car": "Kia Sportage",
        "location": "Орто-Сай",
        "seller_name": "Tire Market",
        "verified": True,
    },
    {
        "title": "Шланг тормозной задний универсальный",
        "part_number": "BRAKE-HOSE-UNI",
        "price": 1200,
        "condition": "new",
        "category": "general",
        "car": "универсальные",
        "location": "рынок Кудайберген",
        "seller_name": "Импорт KG",
        "verified": True,
    },
    {
        "title": "Масло моторное 5W-30 синтетика 4 л",
        "part_number": "OIL-5W30-4L",
        "price": 2800,
        "condition": "new",
        "category": "fluids",
        "car": "универсальные",
        "location": "Орто-Сай",
        "seller_name": "Импорт KG",
        "verified": True,
        "description": "Подходит для большинства бензиновых двигателей.",
    },
]


def build_catalog_entries() -> list[dict]:
    out: list[dict] = []
    for i, raw in enumerate(_RAW):
        images = gallery_for_index(i)
        entry = {**raw, "images": images, "image_url": images[0]}
        out.append(entry)
    return out


CATALOG_PARTS = build_catalog_entries()
